name: llms-busybuilders
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - openai
  - transformers
  - langchain
  - chromadb
  - faiss-cpu
  - sentence-transformers
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - requests
  - python-dotenv
  - ipywidgets
  - pyarrow
  - pip:
    - gradio
    - tiktoken
    - langchain-openai
    - langchain-core
    - langchain-community
